### ISSUE TITLE
[Suggestion] Add max txt limit for players.

### ISSUE THREAD

**Issue by xDanub** [fuyutsuki/Texter#102]
**Is your feature request related to a problem? Please describe.**
Yes. When I have this plugin I usually just take away the permission for all players so only ops can make texts, because If I don't, players will spam and abuse the /txt command.

**Describe the solution you'd like**
I would like to see an option in config to set a max_txts: so players have to delete their old txts to create new ones.

**Describe alternatives you've considered**
Taking away the permission from everyone so only ops can /txt.

**Additional context**

**Comment by fuyutsuki** [comment]
Use char and feed in config.
https://github.com/fuyutsuki/Texter/blob/cd9ad8b48ce8659b4948db5c7e5977bd2da61110/resources/config.yml#L15-L25
