### ISSUE TITLE
FloatingTexts disappear except in default world

### ISSUE THREAD

**Issue by joshuasing** [fuyutsuki/Texter#11]
### Version of Pmmp:
PocketMine-MP 1.7dev-937 for Minecraft: PE [REDACTED] (protocol version 3.0.0-ALPHA12)

### Version of texter:
2.3.3

* issue(s):
# **Please Help!** every time the server restarts the floating text is gone!

**Comment by fuyutsuki** [comment]
Dear @joshuasing. 
How to reproduce this issue? please let me.

**Comment by joshuasing** [comment]
i don`t know! when i stop the Pmmp server and then start it again there gone!!

**Comment by fuyutsuki** [comment]
Ok, did you lose the FloatingTexts you added from the file?  
Or is it from the command?

**Comment by joshuasing** [comment]
from the command

**Comment by fuyutsuki** [comment]
How is the number of FloatingTexts?

**Comment by joshuasing** [comment]
when i start the server it does not say anything like that.

**Comment by fuyutsuki** [comment]
Texter is enabled?

**Comment by fuyutsuki** [comment]
Since the same problem does not occur in my environment, so ask in this way.

**Comment by joshuasing** [comment]
yes texter is enabled.
