### ISSUE TITLE
Remove default permission

### ISSUE THREAD

**Issue by isoz** [fuyutsuki/Texter#12]
Please remove default permission for players to be able to place text, since we can't define specific areas where they can place text it's just a grieffing tool. Server owners can assign the permission themselves to players if they so wish.

**Comment by isoz** [comment]
I think just not setting it to default for everybody is fine, I can just add the permission to PurePerms if I want everybody to use it.

**Comment by fuyutsuki** [comment]
Yes, but I think **want all players to handle this plugin (just like a billboard)**.
If you use `PurePerms`, I think that it is possible to execute commands only for specific players, even with the current settings, is not it?

**Comment by isoz** [comment]
Why would you want to have all players place text in your server? People are going to place offensive things in spawn and grieff unless you only play with your friends, which is unlikely.

**Comment by fuyutsuki** [comment]
That's right. So, my idea and you or another server operator's idea will be different.
Therefore, if you want to restrict more strictly as you say, I'd like you to use `PurePerms` etc. and limit by each servers.

**Comment by fuyutsuki** [comment]
Please give us your opinion!

**Comment by fuyutsuki** [comment]
Since there is no reply, this issue closes. Please reply when there is time.
