### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZippingBoat9588** [fuyutsuki/Texter#129]
![Screenshot_20220814-140808](https://user-images.githubusercontent.com/104681534/184536148-9206d950-3847-4c28-9104-ec0c213c1593.png)
@fuyutsuki

**Comment by sulimanzeen** [comment]
I found this bug too. and here is the crash dump for better logs
https://crash.pmmp.io/view/7361354

**Comment by fuyutsuki** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. Add floating text to the world
2. `/txt edit`
3. Select the floating text you added in 1.
4. Change the unique identifier of a floating text
