### ISSUE TITLE
NEW PM4 UPDATE

### ISSUE THREAD

**Issue by DrPerkyLegit** [fuyutsuki/Texter#131]
**Describe the bug**
Update to player packets with newest bedrock protocol update
**To Reproduce**
1. Go to 'pocketmine github install newest version'
2. Set server and everything up
3. Go ingame and use "/txt add"
4. complete form hit enter and see server crash

**Expected behavior**
Floating text to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/116128211/198046800-777a69a1-1b00-4ec6-a063-a05c3396918a.png)

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - PMMP: [e.g. 4.10.0]
 - Plugins: [e.g. Texter, DevTools, custom core]

**Additional context**
[Add any other context about the problem here.](https://github.com/pmmp/BedrockProtocol/releases/tag/14.0.0%2Bbedrock-1.19.40)

**Comment by mri4ards** [comment]
same problem

**Comment by sdsd20021127** [comment]
https://github.com/sdsd20021127/Texter/releases

i updated it for pm 4.10.0 and try it =)

**Comment by fuyutsuki** [comment]
This problem will be fixed in 4.1.8.
