### ISSUE TITLE
No text is showing when creating or editing a floating text

### ISSUE THREAD

**Issue by CallMeYuuuu** [fuyutsuki/Texter#133]
**Describe the bug**
No text is showing when creating or editing a floating text

**To Reproduce**
1. create a floating text

**Expected behavior**
Text is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/44119696/203866632-49b03376-3267-4ab3-a227-a116492897ec.png)
![image](https://user-images.githubusercontent.com/44119696/203866673-16d5596c-d6a1-4f04-aafe-065bda014a09.png)

**Server (please complete the following information):**
 - OS: Ubuntu 22.4
 - PMMP: 4.10.1
 - Plugins: Texter, DevTools, Slapper, PurePerms, MultiWorld

**Additional context**
I tried restarting, recreating and editing the text but without any changes

**Comment by fuyutsuki** [comment]
Hi @CallMeYuuuu,

Try re-downloading the plugin from [Poggit](https://github.com/fuyutsuki/Texter/releases/tag/release%2Fv4.1.8).
If that doesn't help, please let me know what version of Texter you have

**Comment by CallMeYuuuu** [comment]
I use the latest version of texter. I downloaded it from poggit the same day I had the issue.

**Comment by fuyutsuki** [comment]
Please tell me the folder name of the world you are using (`worlds/*`) and send the files in the `plugin_data/Texter` folder

**Comment by fuyutsuki** [comment]
It's been three weeks since my last reply, so closing it
