### ISSUE TITLE
Texter remove text usage message not being displayed correctly

### ISSUE THREAD

**Issue by CallMeYuuuu** [fuyutsuki/Texter#134]
**Describe the bug**
Texter remove text usage message not being displayed correctly

**To Reproduce**
1. Do /txt r

**Expected behavior**
Correct message is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/44119696/203866972-a3d9e2ef-0e9b-4519-914c-100d903a2ec9.png)

**Comment by fuyutsuki** [comment]
Looks like the same problem as #133. Please use that one for future conversations
