### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by NdaruAjaa** [fuyutsuki/Texter#143]
![Screenshot_2023-06-25-06-43-24-468-edit_com android chrome](https://github.com/fuyutsuki/Texter/assets/120300909/ed8737a7-64ea-4ee4-8cf5-cc1a76015024)
Is it a bug?

**Comment by fuyutsuki** [comment]
Hi, @NdaruAjaa,  
Are you using files downloaded from Poggit? If you download from Poggit and get a similar error, please let me know.

**Comment by NdaruAjaa** [comment]
Yes I downloaded from poggit and error if I download from github release no errors occur

**Comment by NdaruAjaa** [comment]
Thank you for the help
