### ISSUE TITLE
No {line} \n support?

### ISSUE THREAD

**Issue by SillierShark195** [fuyutsuki/Texter#147]

**Comment by fuyutsuki** [comment]
Hi @SillierShark195,

To start a new line, type `#` instead of `\n`.

**Comment by SillierShark195** [comment]
> Thanks, but the issue tracker is not intended for support. Please re-post it to the [Discussion](https://github.com/fuyutsuki/Texter/discussions).

Ah Rip im tryna make f top text using #1 rewards

**Comment by fuyutsuki** [comment]
Are you saying want to enter a string containing `#`?
