### ISSUE TITLE
Texter with WaterdogPE

### ISSUE THREAD

**Issue by ClydeplayzYT590** [fuyutsuki/Texter#148]
**Describe the bug**
Doesn't work on [WaterdogPE](https://waterdog.dev/), kicks the player without any errors on PocketMine-MP console but has errors on the WaterdogPE console logs

**To Reproduce**
1. Go to a WaterdogPE server with PocketMine-MP downstream that has the Texter plugin
2. Make a floating text

**Expected behavior**
To work

**Screenshots**
![XRecorder_03082023_104657](https://github.com/fuyutsuki/Texter/assets/86055764/4e1b412d-1bdd-4001-ba37-4b9a2e348f01)

**Server (please complete the following information):**
 - OS: Linux
 - PMMP: 5.4.0
 - Plugins: AntiServerStop, BetterBan, Chat4Staff, DummyItemsBlocks, EasyEdit, EpicCustomAlerts, Fireworks, FormAPI, FormImagesFix, Hacks, HumanNPC, HypixelBow, MOTDShuffle, MultiWorld, RankSystem, ScoreHud, TransferAPI, theSpawn, Texter

**Comment by fuyutsuki** [comment]
Hi @ClydeplayzYT590,
What is the version of WaterdogPE?

**Comment by ClydeplayzYT590** [comment]
v2.0.0

**Comment by xxFLORII** [comment]
@fuyutsuki the issue should be fixed in [431d69c](https://github.com/fuyutsuki/Texter/commit/431d69ced737c1cc89cacd67ed1f195dca727b32)

it work's with and without WaterdogPE
