### ISSUE TITLE
Plugin Commands Doesn't Work

### ISSUE THREAD

**Issue by CupidonSauce173** [fuyutsuki/Texter#15]
The commands of the plugin doesn't work but the server find and activate the plugin.
We see the /txt and /txtadm but when we do one of these commands, nothing happen.

Pocketmine Informations
PocketMine-MP 1.7dev-1001 API version 3.0.0-ALPHA12 for minecraft: PE v1.4.0 (protocal version 261)
I also use TeaSpoon but I removed it to try the plugin and it still doesn't work.

Steps
-close the server.
-drop the -master on the plugins file.
-open the server.
-try Texter commands.

There is no server errors, it's like the command is there but it just do nothing.
Thank you for the help.

**Comment by fuyutsuki** [comment]
Hi, @CupidonSauce173.  
Instead of downloading the .zip file directly from Github, please download the phar file built from [Texter distribution page of poggit](https://poggit.pmmp.io/p/Texter).  

If something is still having problems, please reopen this issue.  
Thank you for your report!
