### ISSUE TITLE
loading every world on startup

### ISSUE THREAD

**Issue by Smorted** [fuyutsuki/Texter#151]
**Describe the bug**

why does Texter load Every world on startup? even if the world does not have any floating texts inside
**To Reproduce**

**Expected behavior**
it should only load the worlds which actually have floating texts inside it

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - PMMP: [e.g. 3.16.0]
 - Plugins: [e.g. Texter, DevTools, ... etc]

**Additional context**

**Comment by fuyutsuki** [comment]
Certainly, it is not necessary to generate all floating texts when the plugin is loaded. I'll fix it.

**Comment by Smorted** [comment]
did you fix it yet? i have made a noop fix by only commenting out the line which loads the worlds but im looking forward to use the proper fix that you will make

**Comment by fuyutsuki** [comment]
Implemented on [4.2.3](https://github.com/fuyutsuki/Texter/releases/tag/v4.2.3(630e5a4))
