### ISSUE TITLE
Crftps disappears

### ISSUE THREAD

**Issue by fuyutsuki** [fuyutsuki/Texter#16]
### 必須項目 (Required item)

* ServerOS: Any OS

* PHP-version: Any PHP

* Minecraft version: MC:Win10Ed. v1.1.5 & MC:PE v1.1.5

* issue(s):
一定時間(?)で浮き文字が消失する
原因不明

**Comment by fuyutsuki** [comment]
> unloadChunk()時にエンティティが消えるからそれでは？
テストしてみましたが、消えませんでした

**Comment by wakame0731** [comment]
Genisysproの最近のコミットの中にfloatingtextparticleが数分で消えるのを修正ってのがありました。なにか手掛かりになりませんかね

**Comment by fuyutsuki** [comment]
@wakame0731 ありがとうございます、どうやらItemEntityだと5分ちょっとで消えるようです
コミット一覧を見ればよかった…
