### ISSUE TITLE
Can you please Turn off version detection？

### ISSUE THREAD

**Issue by Atara6431** [fuyutsuki/Texter#163]
![image](https://github.com/user-attachments/assets/8c817cae-f0fa-422d-bac0-c74efc1d498a)
If turn off version detection，It's no need to update plugin, which still can be used.

**Comment by fuyutsuki** [comment]
You can disable version checking by config.yml `check.update` to `false`!

https://github.com/fuyutsuki/Texter/blob/fecd04e3910519360b3cea610e2f05406dffac59/resources/config.yml#L7

**Comment by Atara6431** [comment]
Thanks<(￣︶￣)>
