### ISSUE TITLE
Texter v2.4.0 debug

### ISSUE THREAD

**Issue by servantthought** [fuyutsuki/Texter#19]
### 必須項目 (Required items)

Enabling Texter v2.4.0 04.06 10:25:23 [Server] Server thread/CRITICAL Error: "Class 'tokyo\pmmp\libform\FormApi' not found" (EXCEPTION) in "Texter_v2.4.0.phar/src/tokyo/pmmp/Texter/Core" at line 227 04.06 10:25:23 [Server] Server thread/DEBUG #0 Texter_v2.4.0.phar/src/tokyo/pmmp/Texter/Core(115): tokyo\pmmp\Texter\Core->initFormApi() 04.06 10:25:23 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(90): tokyo\pmmp\Texter\Core->onEnable() 04.06 10:25:23 [Server] Server 
thread/DEBUG #2 src/pocketmine/plugin/PharPluginLoader(127): pocketmine\plugin\PluginBase->setEnabled(boolean 1) 04.06 10:25:23 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(578): pocketmine\plugin\PharPluginLoader->enablePlugin(tokyo\pmmp\Texter\Core object) 04.06 10:25:23 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1951): pocketmine\plugin\PluginManager->enablePlugin(tokyo\pmmp\Texter\Core object) 04.06 10:25:23 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1937): pocketmine\Server->enablePlugin(tokyo\pmmp\Texter\Core object) 04.06 10:25:23 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1731): pocketmine\Server->enablePlugins(integer 1) 04.06 10:25:23 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(290): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/) 04.06 10:25:23 [Server] Server thread/DEBUG #8 /pmmp_1079_1.4.0.phar(1): require(string phar:///pmmp_1079_1.4.0.phar/src/pocketmine/PocketMine.php) 04.06 10:25:23 [Server] Server thread/INFO Disabling Texter v2.4.0

* ServerOS:

* PHP version:

* Minecraft version:

* Texter version:
Texter v2.4.0

* issue(s):

**Comment by fuyutsuki** [comment]
2.4.0 is **under development**. please wait.
