### ISSUE TITLE
[poggit] Naming text

### ISSUE THREAD

**Issue by fuyutsuki** [fuyutsuki/Texter#2]
### 必須項目 (Required items)

* ServerOS:

* PHP version:

* Minecraft version: v.1.2.8~

* Texter version: v2.2.6~

* issue(s):
> Its okay but why their ID you should do main name then the text you want but the main name not their so we can remember what text put their with a main name as well do /txt list show all the txt with the names.

***This issue was created by Poggit user's comment.*** (by @kokoplayz )
However, this issue is created if I think needs it.
If you do not need it, this issue will be **closed**.

**Comment by fuyutsuki** [comment]
@kokoplayz Is the "Main name" a unique string to write in crfts.json?
Please let us your opinion!

**Comment by fuyutsuki** [comment]
I will put this issue on hold until I receive a reply.

**Comment by kokoplayz** [comment]
I mean The ID changes when server reload or restarts & its shows in front of the text the least time i used it since i been buzy but the thing it I like it to be like floating Text plugin Spogit.

**Comment by fuyutsuki** [comment]
Do you mean that you should be able to name that text unique name?

**Comment by kokoplayz** [comment]
Sorry i was reediting it

**Comment by fuyutsuki** [comment]
I understand.  
Thank you for having detailed explanation.  
It will be implemented in v2.3.0.  
Please wait for a while.

**Comment by kokoplayz** [comment]
Thank you very much

**Comment by fuyutsuki** [comment]
Dear @kokoplayz 
As you know, id is displayed next to the title.
However, if you use the suggested title, if you display it side by side like id, **the title part becomes redundant**.  
We also considered implementing commands like `/txt list`, but if there are hundreds of FloatingTexts in the world, we must identify them from a huge amount of floating characters.  
Do you have any solutions?

**Comment by kokoplayz** [comment]
when you create a text when you name it That what should come up your only allowed to use its like make a secound text put same name its will say their one ready with that name so wont need id

**Comment by fuyutsuki** [comment]
@kokoplayz You can speak in your native language, do not you?

**Comment by kokoplayz** [comment]
idk

**Comment by fuyutsuki** [comment]
@kokoplayz May you explain in a bit more detail? I'm sorry I did not understand.

**Comment by fuyutsuki** [comment]
I will close because there is no response sorry
