### ISSUE TITLE
FTP is spawned in all worlds

### ISSUE THREAD

**Issue by GamakCZ** [fuyutsuki/Texter#23]
### 必須項目 (Required items)

* ServerOS: Debian 9

* PHP version: 7.2

* Minecraft version: 1.4 (win10)

* Texter version: 2.4.1

* issue(s):
When I spawn FTP in level Spawn, is in all worlds on server. I want it only in level Spawn.

**Comment by GamakCZ** [comment]
ftp = floating text particle

**Comment by fuyutsuki** [comment]
I'll check it. Thank you for your report!

**Comment by GamakCZ** [comment]
I found out that the bug is on my side but I discovered another bug. When is FTP in level with name 'Lobby' and folder name 'Lobby' is too in level 'Lobby' with folder name 'Spawn'
