### ISSUE TITLE
API for multilanguage?

### ISSUE THREAD

**Issue by NycuRO** [fuyutsuki/Texter#25]
How can i check if player have other language? Or not exist an api for that?

**Comment by fuyutsuki** [comment]
Do you mean "I want to send messages that match the language of the player, not the language of the server"?

**Comment by NycuRO** [comment]
Yes

**Comment by fuyutsuki** [comment]
Ok, I'll implement this on v2.4.2

**Comment by fuyutsuki** [comment]
Done this on 3.0.0

**Comment by NycuRO** [comment]
Actually not. I mean about on floatingtext support multilanguage, like this plugin on nukkit: https://nukkitx.com/resources/holograms.42/

Not about commands language. @fuyutsuki

**Comment by fuyutsuki** [comment]
@NycuRO 
It's not planned to be provided by the standard function.
Please implement by yourself using TexterApi etc.
