### ISSUE TITLE
Floating texts would disappear after a restart in the new update 3.0.2 POCKETMINE!

### ISSUE THREAD

**Issue by vandermarelruben** [fuyutsuki/Texter#27]
Dear fuyutsuki,
After the new pocketmine update (3.0.2) whenever I add a floating text, it would disappear after i restart my server. 
Is there any way to fix this?
Any help would be appropriated.

Thank you.

-Ruben

**Comment by fuyutsuki** [comment]
Can I show your `crfts.json` and `fts.json`?

**Comment by fuyutsuki** [comment]
I close this issue because there is no response. Please reopen this issue if you notice this message.
