### ISSUE TITLE
plugin wont load

### ISSUE THREAD

**Issue by cosmicAtom** [fuyutsuki/Texter#29]
### 必須項目 (Required items)

* ServerOS: Win10 Pro

* PHP version: php7.2 (64bit)

* Minecraft version: MC:Win10Ed. v1.4

* Texter version: Texter v 2.4.1 or latest from poggit

* issue(s): The plugin wont load due to this error:
` [Server thread/CRITICAL]: Error: "Class 'tokyo\pmmp\libform\FormApi' not found" (EXCEPTION) in "_Texter/src/tokyo/pmmp/Texter/Core" at line 200`
and as far as i know... FormAPI is installed.

**Comment by fuyutsuki** [comment]
Dear @cosmicAtom.  
I couldn't reproduce this issue. Please try reinstalling the plugin as follows.  
1. Remove plugins/Texter-dev**.phar
2. Remove plugin_data/Texter folder
3. Redownload from poggit

**Comment by cosmicAtom** [comment]
Fixed

**Comment by fuyutsuki** [comment]
Ok, thank you for your report!
