### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Shelly7w7** [fuyutsuki/Texter#30]
### 必須項目 (Required items)

* ServerOS: Win10

* PHP version: 7.2 i think 

* Minecraft version: 1.5.2

* Texter version: latest commit of 3.0.0

* issue(s): ```Enabling Texter v2.4.2
29.07 09:30:33 [Server] Server thread/CRITICAL Error: "Class 'tokyo\pmmp\libform\FormApi' not found" (EXCEPTION) in "Texter-master/src/tokyo/pmmp/Texter/Core" at line 200```

**Comment by fuyutsuki** [comment]
Please reference to #29
