### ISSUE TITLE
/txt move error

### ISSUE THREAD

**Issue by SuperAdam47** [fuyutsuki/Texter#31]
### 必須項目 (Required items)

* ServerOS: Linux

* PHP version: 7.2

* Minecraft version: 1.5

* Texter version: lastest

* issue(s):
![image](https://user-images.githubusercontent.com/16169771/43409617-1cb6bd46-942d-11e8-9178-7d8a0a3073f6.png)

**Comment by fuyutsuki** [comment]
Please wait by checking it

**Comment by SuperAdam47** [comment]
ok

**Comment by SuperAdam47** [comment]
fix pls

**Comment by fuyutsuki** [comment]
Oops, sorry to be late this message. this is caused by specification of MC:BE changes.  
I'll fix this in today. please wait a bit!

**Comment by SuperAdam47** [comment]
thank you for your interest
