### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SuperAdam47** [fuyutsuki/Texter#32]
### 必須項目 (Required items)

* ServerOS: linux

* PHP version: 7.2

* Minecraft version: 1.52

* Texter version: Texter_dev-66

* issue(s):

Error: "Class 'pocketmine\lang\Language' not found" (EXCEPTION) in "Texter_dev-66.phar/src/tokyo/pmmp/Texter/Core" at line 110

**Comment by fuyutsuki** [comment]
Oops, I forgot to update the API version.  
It will be resolved if you update pmmp. I'm sorry for troubling you.

**Comment by SuperAdam47** [comment]
but pmmp is so bad software

**Comment by fuyutsuki** [comment]
What's using

**Comment by SuperAdam47** [comment]
Altay Software

**Comment by fuyutsuki** [comment]
Please use pmmp or new altay

**Comment by SuperAdam47** [comment]
ok
