### ISSUE TITLE
Texter text not showing up

### ISSUE THREAD

**Issue by Snickerzzz** [fuyutsuki/Texter#33]
* ServerOS: No idea, server host hosts it.

* PHP version: Same as above not really sure.

* Minecraft version:  Windows 10 **v1.5.0**

* Texter version: **v2.4.1** (I tried to update to the newest version but it didn't work)

* issue(s): My text won't appear at all. I try to create it and it won't show up or anything. When I click the finish button I don't get a message or anything saying complete (not sure if I'm supposed to). I've checked the console for errors and I didn't get any.

```bash
09.08 22:46:43 [Server] Server thread/INFO [Texter] Crft: 3 texts / Ft: 0 texts have been generated
09.08 22:46:43 [Server] Server thread/NOTICE [Texter] URL: https://github.com/fuyutsuki/Texter/releases/tag/release/v2.4.2
09.08 22:46:43 [Server] Server thread/NOTICE [Texter] Update is available
09.08 22:46:43 [Server] Server thread/NOTICE [Texter] Latest version: v2.4.2 / Current version: v2.4.1
```

**Comment by fuyutsuki** [comment]
Match the name of the world in the `world folder` that contains the world's data with the name of the world.

**Comment by Snickerzzz** [comment]
Hello,

I probably sound annoying and dumb, but I don't get what you mean. Sorry to be annoying.

**Comment by fuyutsuki** [comment]
Dear @Snickerzzz.   
- Please write the server software name and version you are using. (you can also include the result of hitting `/ver` with the console)  
- Please paste the file (crfts.json or fts.json) that stores the text here  
- Please tell me the folder name in the `worlds` folder

**Comment by Snickerzzz** [comment]
- This server is running PocketMine-MP 3.1.3 for Minecraft: PE v1.5.0 (protocol version 274)

- crfts.json: https://pastebin.com/WHY5prr2

- fts.json: https://pastebin.com/jNvze219

- Server-Spawn

**Comment by fuyutsuki** [comment]
Thanks, please wait for a while...

**Comment by fuyutsuki** [comment]
Dear @Snickerzzz.
Thank you for reporting the issue. since it was a plugin mistake, I`ll release a modified 2.4.3.  
We apologize for the inconvenience.

**Comment by Snickerzzz** [comment]
@fuyutsuki When I do /txt or /txtadm nothing appears. I don't get any errors in config either.

**Comment by fuyutsuki** [comment]
@Snickerzzz Where did you download from?

**Comment by Snickerzzz** [comment]
https://github.com/fuyutsuki/Texter

I did the green "clone and download" tab and downloaded the zip and then moved that folder into my plugins folder for devtools to load it.

**Comment by fuyutsuki** [comment]
Also, please download from [poggit](https://poggit.pmmp.io) in the future.

**Comment by Snickerzzz** [comment]
Yes, I honestly don't know it's not working... I tried it and it still is doing the thing where I do /txt add, do all the info and then it just doesn't add anything after. Can you come on my server and test it or something because I don't know what I'm doing wrong lol. No errors just this: 
10.08 21:47:31 [Server] Server thread/INFO [Texter] Crft: 3 texts / Ft: 0 texts have been generated
10.08 21:47:31 [Server] Server thread/NOTICE [Texter] Latest version: v2.4.3 / No update needed

**Comment by Snickerzzz** [comment]
When I tried do /txt list it said "An unknown error occurred while attempting to perform this command"

**Comment by fuyutsuki** [comment]
Okay, I think I`ll try accessing your server.  
Is there a means of communication for teaching ip and port?

**Comment by Snickerzzz** [comment]
Yes, do you have discord so I can send it to you?

Snickerzzz#8877

**Comment by fuyutsuki** [comment]
Because there is no contact to Discord, I close it as resolved.
