### ISSUE TITLE
Add variables

### ISSUE THREAD

**Issue by SuperAdam47** [fuyutsuki/Texter#34]
![image](https://user-images.githubusercontent.com/16169771/44097453-79a0ac46-9fe6-11e8-847a-a9299b216702.png)

**Comment by fuyutsuki** [comment]
Is it the function you want? It can be implemented using TexterAPI.

**Comment by fuyutsuki** [comment]
?????

**Comment by SuperAdam47** [comment]
what the TexterAPI

**Comment by fuyutsuki** [comment]
Since the function to acquire information every few seconds is not implemented by default, its necessary to implement by yourself using Texter's API.
