### ISSUE TITLE
add 4.0.0 branch

### ISSUE THREAD

**Issue by SuperAdam47** [fuyutsuki/Texter#36]
### 必須項目 (Required items)

* ServerOS:

* PHP version:

* Minecraft version:

* Texter version:

* issue(s):

**Comment by fuyutsuki** [comment]
Thank you for your report!  
In conjunction with the release of v3.0.0, we plan to release it for API4.0.0.

**Comment by fuyutsuki** [comment]
[`4.0` branch](https://github.com/fuyutsuki/Texter/tree/4.0) has been adapted to API 4.0.0.
To use with phar, [download](https://poggit.pmmp.io/ci/fuyutsuki/Texter/Texter) the build of 4.0 branch from poggit.
![image](https://user-images.githubusercontent.com/16377174/46312326-b6435b00-c5ff-11e8-9eed-c6cb18cdbd55.png)
