### ISSUE TITLE
Eooe

### ISSUE THREAD

**Issue by Shelly7w7** [fuyutsuki/Texter#44]
### 必須項目 (Required items)

* ServerOS: Linux

* PHP version: 7.2

* Minecraft version: 1.8.0

* Texter version: Latest master branch

* issue(s): ``` Server thread/CRITICAL TypeError: "Argument 1 passed to tokyo\pmmp\Texter\text\FloatingText::__construct() must be of the type string, integer given, called in phar:///plugins/Texter_dev-103.phar/src/tokyo/pmmp/Texter/task/PrepareTextsTask.php on line 92" (EXCEPTION) in "Texter_dev-103.phar/src/tokyo/pmmp/Texter/text/FloatingText" at line 68```

**Comment by fuyutsuki** [comment]
Thank you for your report. I wlll fix it as soon as possible!
