### ISSUE TITLE
Text not showing/creating

### ISSUE THREAD

**Issue by JoePlayz** [fuyutsuki/Texter#45]
Downloaded the latest one off poggit, changed the world name in uft to my world name, console said 3 text generated but when I went on and did /txt list, it said no text has been found and I did /txt add and filled in the UI, clicking submit didn’t create anything, I checked the plugin folder and nothing has been changed. I reloaded/restarted the server and still didn’t work. Please fix this issue!

**Comment by JoePlayz** [comment]
Server Version: PocketMine-MP 3.5.2
PHP Version: 7
VPS OS: Linux Ubuntu
Texter Version 3.0.6

Plugin List: BuilderTools v1.1.0-beta2, PurePerms v1.4.2-c2a, MapImageEngine v1.1.2, DevTools v1.13.0, ClearLagg v1.1.0, BasicHUD v1.0.8, ScoreHud v2.0.0, KDR v1.0.0, CustomWhitelistReason v1.0.3, ManyWorlds v2.2.0, FormAPI v1.2.0, GuiShop v1.0.0-BETA2, PiggyCustomEnchants v1.2.0, EconomyAPI v5.7.2, GappleCooldown v2.0.1, PocketVote v2.1.5, PortalsPE v1.1.1, Broadcaster v1.5, Festival v1.0.8-dev2, AntiSpamPro v1.4.1, MOTDShuffle v1.1.6, MysteryCrate v6.5.0, MSpawns v2.2, Overvoltage v1.0.0, BuycraftPM v0.5.2, CombatLogger v0.0.6, essentialsTP v1.2.1, TreasureChest v1.2.3, TopVoter v3.1.0, AutoRestarter v1.0.0, EssentialsPE v2.1.0, AdvancedKits v5.2.2, FactionsProBeta v1.4.6, Texter v3.0.6, PureChat v1.4.11

**Comment by fuyutsuki** [comment]
Please show the world name you set and the contents of `ft.json`

**Comment by JoePlayz** [comment]
World name & folder name: faction
Contents of ft.json is default blank

{
}

**Comment by fuyutsuki** [comment]
Oops sorry, I made a mistake. Please tell me the contents of `uft.json`
