### ISSUE TITLE
[Poggit] Hide the text name

### ISSUE THREAD

**Issue by fuyutsuki** [fuyutsuki/Texter#46]
@Wertzui123 Please tell me your opinion on what kind of function you should make it.

**Comment by Wertzui123** [comment]
1. What kind of function? What means that?
2. Whats a ServerOS
3. I think PHP7, so I have pocketmine 3.6.2
4. The last Texter version
5. What do you mean?
Sorry, but I am german and I don't understand everything in English

**Comment by fuyutsuki** [comment]
@Wartzui123  
In Ihrem Testbericht bei Poggit gab es einen Vorschlag für die Funktion "die Namen der Floating-Buchstaben ausblenden".  
Daher wollte ich einen Plan für die Art der Funktion.  
(I used Google Translate)

**Comment by fuyutsuki** [comment]
Wenn Sie nicht wissen, was ich sage, können Sie dieses Problem schließen.

**Comment by Wertzui123** [comment]
Ok, I don't know, but why I shoud close it than? Thanks for the answer in german, but its sound very weard. I think if I wan't to write in English it is the same!

**Comment by fuyutsuki** [comment]
Okay, I'm sorry. Thanks for your response.
