### ISSUE TITLE
A missed api bump item

### ISSUE THREAD

**Issue by naja82** [fuyutsuki/Texter#48]
please change line 55, 56, 57 at tokyo\pmmp\Texter\text\UnremovableFloatingText from $this->pos->x to $this->x same as tokyo\pmmp\Texter\text\FloatingText
I tried to code my plugin that depends on Texter and then I found this small bug
This mistake is so small for a PR so I opened an issue
sorry for any English grammar incorrection if there is

**Comment by fuyutsuki** [comment]
Thank you for your report! yes, that's my mistake. I'll fix as soon as possibly.
