### ISSUE TITLE
Text name

### ISSUE THREAD

**Issue by tdubz1** [fuyutsuki/Texter#50]
Hi there,

Is there anyway to get rid of the text name because it looks quite ugly and unprofessional on my server and I really need a floating text plugin. 

Thanks,

tdubz1

**Comment by ql3** [comment]
Hi @tdubz1, are you sure that you want to remove the name of FloatingTexts?

**Comment by fuyutsuki** [comment]
Hi @tdubz1, are you sure that you want to remove the name of FloatingTexts?

**Comment by tdubz1** [comment]
Yes

**Comment by fuyutsuki** [comment]
The name of the FloatingText is invisible to players who are not OP or who don't possess the FloatingText.  
Do you want to do anything else?

**Comment by fuyutsuki** [comment]
This issue is closed because there is no reply for a certain period. If you want to open it again, please let me know.
