### ISSUE TITLE
Anyone can use /txt

### ISSUE THREAD

**Issue by LiaamDev** [fuyutsuki/Texter#51]
### 必須項目 (Required items)

* ServerOS: Debian

* PHP version: 7.2 64 bit

* Minecraft version: MC:iOs v1.1.4

* Texter version: 3.0.8

* issue(s): Anyone can use /txt commands, meaning normal players can create floating text wherever they want.

**Comment by fuyutsuki** [comment]
Hi @LiaamDev.  
Yes, that's right. Why? because I want yours to use FloatingTexts like a signboards.

However, I also know that there are some servers that only ops want to be able to use.  
So I will add config that manage permission.

**Comment by fuyutsuki** [comment]
related #12

**Comment by LiaamDev** [comment]
Thanks, that's great.
