### ISSUE TITLE
Texter ID

### ISSUE THREAD

**Issue by treehousemc1** [fuyutsuki/Texter#6]
Hi. Can you please remove texter ID and add cmd do check id so people will know it's id

**Comment by fuyutsuki** [comment]
Hi @treehousemc1.  
In Texter 2.3.0 I think that it will be displayed as shown below, but is id unnecessary?
```
Title
Text line1
Text line2
[UniqueString]
```
If you wish to fix it, install it from `crfts.json` and ID will be hidden.

**Comment by fuyutsuki** [comment]
Also, for player who do not have permission to erase FloatingTexts, IDs are made invisible automatically.

**Comment by treehousemc1** [comment]
change 
"world": {
    "TextName1": {
      "Xvec": 128,
      "Yvec": 90,
      "Zvec": 128,
      "TITLE": "Title",
      "TEXT": "Text(New line with #)"

to

Title
Text line1
Text line2
[UniqueString]
?

**Comment by fuyutsuki** [comment]
The example is as follows
```
Title
Text(New line with 
)
[TextName1]
```

**Comment by treehousemc1** [comment]
i dont understand

**Comment by fuyutsuki** [comment]
In Texter 2.3.0, it is displayed without ID by writing to `crfts.json` as follows.
### crfts.json
```json
"world": {
  "TextName1": {
    "Xvec": 128,
    "Yvec": 90,
    "Zvec": 128,
    "TITLE": "Title",
    "TEXT": "Text(New line with #)"
  }
}
```
### Output
```
Title
Text(New line with 
)
```
Also, if added by command, data will be added to `fts.json`.
ID is displayed because it performs operations such as deletion.
