### ISSUE TITLE
textes resseting after manual change

### ISSUE THREAD

**Issue by dearminder** [fuyutsuki/Texter#60]
### 必須項目 (Required items)

* ServerOS:
Windows

* PHP version:
7.3.0

* Minecraft version:
Any

* Texter version:
Any

* issue(s):
The floaties are annoying to edit with commands.When you try edit it manualy via config file server dont load any of floaties

**Comment by fuyutsuki** [comment]
Did you edit the file while the server was started?

**Comment by dearminder** [comment]
On enabled. But i am now confused, When i tried on phone even when server was disabled (i think) using diffrent text editor it was reseting, but on pc using notepad++ on disabled it saved

**Comment by fuyutsuki** [comment]
It seems that you did not reflect the text editing on your phone, or it was sent halfway.
