### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Kauso8507** [fuyutsuki/Texter#62]
please add perms!

**Comment by fuyutsuki** [comment]
Please tell me more specifically…

**Comment by dearminder** [comment]
Yea i also noticed it, texter.command.txt should be set to op not true

**Comment by fuyutsuki** [comment]
If you only want to use op, you can configure it in Config

**Comment by fuyutsuki** [comment]
This issue closed because there is no reply from the proposer. Please reply if there is anything else
