### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [fuyutsuki/Texter#63]
LeaderBoards Idea
Can you make a auto updating leaderboard?
For like Factions, Economy, Bounties, Kills, Deaths etc etc
Example
Top Factions
1. TopFaction - 99999999999999999999 STR
2. Da2ndBestFaction - 1937 STR
3. JoinMyFaction - 666 STR
Top Economy
1. IAmOwnerICanDoAnything - 999999999999$
2. Ishouldbebest - 1000000$
3. IAMBEST - 0$

**Comment by fuyutsuki** [comment]
This is a plugin that makes FloatingTextParticle easier to use, not a leaderboard plugin. If you want to use leaderboard, please consider using the following TexterAPI(s).
[manage FloatingTexts](https://github.com/fuyutsuki/Texter/blob/master/src/tokyo/pmmp/Texter/text/FloatingText.php)
[Control the world movement on the Texter side etc](https://github.com/fuyutsuki/Texter/blob/master/src/tokyo/pmmp/Texter/TexterApi.php)

**Comment by ZZWILLIAMXXTrue** [comment]
Ok thanks
