### ISSUE TITLE
add option to move a text to another position

### ISSUE THREAD

**Issue by ghost** [fuyutsuki/Texter#70]

**Comment by fuyutsuki** [comment]
Okay, I'll implements this with 3.5.0 (next minor update)

**Comment by GianC-Dev** [comment]
added.

**Comment by fuyutsuki** [comment]
Nope...

**Comment by qbaddev** [comment]
I am connected to the discussion. **Add please**

**Comment by fuyutsuki** [comment]
@qbaddev Even now, it is possible to move FloatingTexts with the /txt move command.  
This issue only adds an option to specify coordinates.  

Also, since this plugin is maintained by only me, it will take some time to fulfill the request.

**Comment by qbaddev** [comment]
@fuyutsuki , snq
