### ISSUE TITLE
Player Permissions

### ISSUE THREAD

**Issue by MonoAdrian23** [fuyutsuki/Texter#75]
Players have Permissions to create Floating Textes without Permissions.
How can i set this to false?
Pocketmine 3.11.5
Texter Version Latest

**Comment by fuyutsuki** [comment]
https://github.com/fuyutsuki/Texter/blob/21ed1c83281a5cad8e6b7ef19407ddcdf2927063/resources/config.yml#L13

Please change it in plugin_data\Texter\config.yml to `true`

**Comment by MonoAdrian23** [comment]
Oh i havent seen this
Sorry 
Thank you for Help

**Comment by fuyutsuki** [comment]
You're welcome <3
