### ISSUE TITLE
Cannot load the plugin

### ISSUE THREAD

**Issue by minijaham** [fuyutsuki/Texter#80]
17.04 23:43:42 [Server] Server thread/ERROR Could not load plugin 'Texter': Incompatible network protocol version (plugin requires one of: 388, 389)

After the pmmp's new release, the texter plugin cannot load.

**Comment by fuyutsuki** [comment]
Hi, @minijaham.  

The message is a failsafe in case of protocol changes. I was planning to update Texter as soon as pmmp's new version released, so I'll let you know when it is updated.

Thank you for your report.

**Comment by fuyutsuki** [comment]
Now I just release v3.4.6. sorry for late.
https://github.com/fuyutsuki/Texter/releases/tag/release%2Fv3.4.6
