### ISSUE TITLE
Texter 3.4.6 not working

### ISSUE THREAD

**Issue by Kochengg** [fuyutsuki/Texter#82]
please fix :(

**Comment by fuyutsuki** [comment]
Please provide detailed information as the template.

**Comment by Kochengg** [comment]
When i installed Texter ver 3.4.6, my console say: WARNING: "Please install
Texter at: (texter ofc link)

And when i go to game, i use /txt, and nothing happens :( in console they
disabled, but in game they work just on the command list, not to use

**Comment by fuyutsuki** [comment]
Try re-download from [here](https://poggit.pmmp.io/r/82828/Texter_v3.4.6.phar)

**Comment by Kochengg** [comment]
Error again

**Comment by fuyutsuki** [comment]
Please paste the error displayed on the console as it is here

**Comment by Kochengg** [comment]
Enabling Texter v3.4.6
18.04 04:24:01 [Server] Server thread/CRITICAL ErrorException: "include(phar:///plugins/Texter.phar/src/tokyo/pmmp/Texter/EventListener.php): failed to open stream: phar error: Cannot open phar archive "/plugins/Texter.phar" for reading" (EXCEPTION) in "vendor/pocketmine/classloader/src/BaseClassLoader" at line 138
18.04 04:24:01 [Server] Server thread/DEBUG #0 vendor/pocketmine/classloader/src/BaseClassLoader(138): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[266] include(phar:///plugins/Texter.ph, string[120] phar:///custom.phar/vendor/pocket, integer 138, array[2])
18.04 04:24:01 [Server] Server thread/DEBUG #1 vendor/pocketmine/classloader/src/BaseClassLoader(138): include()
18.04 04:24:01 [Server] Server thread/DEBUG #2 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[31] tokyo\pmmp\Texter\EventListener)
18.04 04:24:01 [Server] Server thread/DEBUG #3 (): BaseClassLoader->{closure}(string[31] tokyo\pmmp\Texter\EventListener)
18.04 04:24:01 [Server] Server thread/DEBUG #4 plugins/Texter.phar/src/tokyo/pmmp/Texter/Core(66): spl_autoload_call(string[31] tokyo\pmmp\Texter\EventListener)
18.04 04:24:01 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(115): tokyo\pmmp\Texter\Core->onEnable()
18.04 04:24:01 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
18.04 04:24:01 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object tokyo\pmmp\Texter\Core)
18.04 04:24:01 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object tokyo\pmmp\Texter\Core)
18.04 04:24:01 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1852): pocketmine\Server->enablePlugins(integer 1)
18.04 04:24:01 [Server] Server thread/DEBUG #10 src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
18.04 04:24:01 [Server] Server thread/DEBUG #11 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\defaults\ReloadCommand->execute(object pocketmine\Player, string[6] reload, array[0])
18.04 04:24:01 [Server] Server thread/DEBUG #12 src/pocketmine/Server(1807): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] reload)
18.04 04:24:01 [Server] Server thread/DEBUG #13 src/pocketmine/Player(2218): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] reload)
18.04 04:24:01 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[7] /reload)
18.04 04:24:01 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
18.04 04:24:01 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
18.04 04:24:01 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
18.04 04:24:01 [Server] Server thread/DEBUG #18 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
18.04 04:24:01 [Server] Server thread/DEBUG #19 src/pocketmine/Player(3118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
18.04 04:24:01 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
18.04 04:24:01 [Server] Server thread/DEBUG #21 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 114.122.206.76 44670, object raklib\protocol\EncapsulatedPacket, integer 0)
18.04 04:24:01 [Server] Server thread/DEBUG #22 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
18.04 04:24:01 [Server] Server thread/DEBUG #23 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
18.04 04:24:01 [Server] Server thread/DEBUG #24 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
18.04 04:24:01 [Server] Server thread/DEBUG #25 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
18.04 04:24:01 [Server] Server thread/DEBUG #26 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1587183839.7334)
18.04 04:24:01 [Server] Server thread/DEBUG #27 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
18.04 04:24:01 [Server] Server thread/DEBUG #28 src/pocketmine/Server(1584): pocketmine\Server->start()
18.04 04:24:01 [Server] Server thread/DEBUG #29 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
18.04 04:24:01 [Server] Server thread/DEBUG #30 src/pocketmine/PocketMine(296): pocketmine\server()
18.04 04:24:01 [Server] Server thread/DEBUG #31 (11): require(string[96] phar:///custom.phar/src/pocketmin)
18.04 04:24:01 [Server] Server thread/INFO Disabling Texter v3.4.6

**Comment by Kochengg** [comment]
lol it's working now, i didn't know what happens, but i'ts working, thank you

**Comment by fuyutsuki** [comment]
Do not basically use the reload command.  
This is because there are few compatible plugins. This plugin is also not supported.

**Comment by Kochengg** [comment]
Oh okay, it's work now, thank you very much for your help
