### ISSUE TITLE
Can I make a Korean translation of the plugin?

### ISSUE THREAD

**Issue by minijaham** [fuyutsuki/Texter#83]
Hey! I was helping a server owner who is not fluent in English with his server setup, and I recommended him "Texter" plugin and he loved the features of it, but he was kind of struggling with reading English. So it really came to my mind that the plugin did not have Korean translation. If you don't mind, could I fork the plugin and translate it to Korean? Thanks!

Note: I am fluent in Korean and English

**Comment by fuyutsuki** [comment]
Of course, welcome to contribute :D

**Comment by minijaham** [comment]
Okay :)

**Comment by minijaham** [comment]
Okay, working on it! I will finish the rest tomorrow!

**Comment by minijaham** [comment]
I am done now. Was I supposed to make a fork..? Because I saw how there's just different Readmd.md for other languages

**Comment by fuyutsuki** [comment]
Good job. Could you also translate the language in the game?
https://github.com/minijaham/Texter/blob/master/resources/language/en_us.ini

**Comment by minijaham** [comment]
Yes. Sorry missed that one lol
I'll start working on it right now

**Comment by minijaham** [comment]
Okay I'm done translating!

**Comment by fuyutsuki** [comment]
I'll adjust and commit based on those files, thank you!

**Comment by minijaham** [comment]
Np :)
