### ISSUE TITLE
How to remove [unique txt name] in the text

### ISSUE THREAD

**Issue by rjworks** [fuyutsuki/Texter#86]
How to remove [unique txt name] at the bottom of the text?

**Comment by NormalOcean6686** [comment]
U can`t

**Comment by fuyutsuki** [comment]
Hi @rjworks and @NormalOcean6686.

if remove unique txt name, FloatingTexts can not handle with command.  
Also, the unique name can be seen by the player who added the FloatingText and the OP-players in the specification of Texter, but it is hidden to the player who is not.

So I'm not going to implement it for now. however, I will implement a command that can convert FloatingText that can currently be set with commands to UnremovableFloatingText.

**Comment by rjworks** [comment]
ok that’s fine. i didn’t want normal players to see it
