### ISSUE TITLE
uft.json vs ft.json?

### ISSUE THREAD

**Issue by rjworks** [fuyutsuki/Texter#88]
What's the difference between uft.json and ft.json?

**Comment by fuyutsuki** [comment]
Please refer to [README.md](https://github.com/fuyutsuki/Texter/blob/master/README.md#json-notation).  

In short...

### uft.json
stands for Unremovable-Floating-Text. It cannot be moved or deleted or handled by command.

### ft.json
stands for Floating-Text. It can be moved or deleted or handled by command.
