### ISSUE TITLE
plz update to supprt mcpe 1.16.100

### ISSUE THREAD

**Issue by SupremePox** [fuyutsuki/Texter#96]
[Server thread/ERROR]: Could not load plugin 'Texter': Incompatible network protocol version (plugin requires one of: 388, 389, 390, 407, 408)

**Comment by UnEnanoMas** [comment]
x2

**Comment by fuyutsuki** [comment]
Just released [3.4.11](https://poggit.pmmp.io/r/108633/Texter_3.4.11.phar)!
