### ISSUE TITLE
Plugin is not working with php<7.4

### ISSUE THREAD

**Issue by tomato-0120** [fuyutsuki/Texter#97]
![Screenshot_20201123-124708](https://user-images.githubusercontent.com/61408254/99927916-69e0a980-2d8a-11eb-8c52-35cf0f524d8d.png)

プラグインを入れ、再起動したら上記のようなエラーが出てしまい、最新版のTexterが使えません。
再起動後はサーバーに入れますが、コンソール側にチャットが反映されなかったり他のプラグインが動作しなかったりします。
修正お願いします

**Comment by fuyutsuki** [comment]
@tomato-0120 さん、お問い合わせいただきありがとうございます。

恐らく何かのホスティングサービスでサーバーを開いてらっしゃると思うのですが、原因としてはサーバーのPHPのバージョンが**7.4未満**であることだと思われます。
そのため、まずホスティングサービスの方に連絡して頂き、PHP7.4以降が使えないかどうかを聞いてみてください。

**Comment by tomato-0120** [comment]
承知致しました。
代行されているホスティングサービスの管理者の方に問い合わせてみます。
ご丁寧にありがとうございます。

**Comment by fuyutsuki** [comment]
もしPHP7.4に対応できない場合は、こちらの方で返信していただければ別途7.3用のものを再び作成します。

**Comment by tomato-0120** [comment]
> もしPHP7.4に対応できない場合は、こちらの方で返信していただければ別途7.3用のものを再び作成します。

返信が遅くなりすみません。
php7.4が対応できないため、お手数おかけしますが、7.3用のTexterを作成して頂けると助かります…
お願い致します

**Comment by fuyutsuki** [comment]
[このバージョン](https://poggit.pmmp.io/r/108972/Texter_3.4.11_php7.3.phar)を使用してください(直リンク)
Please use [this version](https://poggit.pmmp.io/r/108972/Texter_3.4.11_php7.3.phar) (direct link)
